export const platforms = [
	{
		platform: 'github',
		color: '#000000',
		logo: 'https://i.postimg.cc/7YXzGwQZ/github.png',
		baseUrl: 'https://github.com/',
	},
	{
		platform: 'linkedin',
		color: '#0A66C2',
		logo: 'https://i.postimg.cc/QNQ1DpQ5/linkedin.png',
		baseUrl: 'https://linkedin.com/in/',
	},
	{
		platform: 'facebook',
		color: '#17A9FD',
		logo: 'https://i.postimg.cc/8z0r4wG8/facebook.png',
		baseUrl: 'https://facebook.com/',
	},
	{
		platform: 'youtube',
		color: '#FF0000',
		logo: 'https://i.postimg.cc/28CvSVGt/youtube.png',
		baseUrl: 'https://www.youtube.com/',
	},
	{
		platform: 'instagram',
		color: '#E4405F',
		logo: 'https://i.postimg.cc/jShzhRF9/instagram.png',
		baseUrl: 'https://www.instagram.com/',
	},
	{
		platform: 'twitter',
		color: '#1DA1F2',
		logo: 'https://i.postimg.cc/ZqMvfnFf/twitterx.png',
		baseUrl: 'https://www.twitter.com/',
	},
	{
		platform: 'pinterest',
		color: '#E60023',
		logo: 'https://i.postimg.cc/520C8TZq/pinterest.png',
		baseUrl: 'https://www.instagram.com/',
	},
	{
		platform: 'snapchat',
		color: '#FFFC00',
		logo: 'https://i.postimg.cc/85xWCc7F/snapchat.png',
		baseUrl: 'https://pin.it/',
	},
	{
		platform: 'tiktok',
		color: '#010101',
		logo: 'https://i.postimg.cc/65rR99t3/tiktok.png',
		baseUrl: 'https://www.tiktok.com/',
	},
	{
		platform: 'whatsapp',
		color: '#25D366',
		logo: 'https://i.postimg.cc/QCL93zz1/whatsapp.png',
		baseUrl: 'https://wa.me/',
	},
	{
		platform: 'reddit',
		color: '#FF4500',
		logo: 'https://i.postimg.cc/cHC6wSpQ/reddit.png',
		baseUrl: 'https://www.reddit.com/r/',
	},
	{
		platform: 'discord',
		color: '#5865F2',
		logo: 'https://i.postimg.cc/c1KBNyvg/discord.png',
		baseUrl: 'https://discord.com/',
	},
	{
		platform: 'spotify',
		color: '#1ED760',
		logo: 'https://i.postimg.cc/c18wbRzf/spotify.png',
		baseUrl: 'https://open.spotify.com/',
	},
	{
		platform: 'twitch',
		color: '#9146FF',
		logo: 'https://i.postimg.cc/g0J6q8RX/twitch.png',
		baseUrl: 'https://www.twitch.tv/',
	},
	{
		platform: 'behance',
		color: '#1769FF',
		logo: 'https://i.postimg.cc/t7QgKVY5/behance.png',
		baseUrl: 'https://www.behance.net/',
	},
	{
		platform: 'dribbble',
		color: '#EA4C89',
		logo: 'https://i.postimg.cc/PfBzX3D6/dribbble.png',
		baseUrl: 'https://dribbble.com/',
	},
	{
		platform: 'medium',
		color: '#00AB6C',
		logo: 'https://i.postimg.cc/MGK1PhkG/medium.png',
		baseUrl: 'https://medium.com/',
	},
	{
		platform: 'vimeo',
		color: '#1AB7EA',
		logo: 'https://i.postimg.cc/W3qFxV5s/vimeo.png',
		baseUrl: 'https://vimeo.com/',
	},
	{
		platform: 'tumblr',
		color: '#36465D',
		logo: 'https://i.postimg.cc/vZGnTpZv/tumblr.png',
		baseUrl: 'https://www.tumblr.com/',
	},
	{
		platform: 'flickr',
		color: '#FF0084',
		logo: 'https://i.postimg.cc/zXKwVCSq/flickr.png',
		baseUrl: 'https://www.flickr.com/',
	},
	{
		platform: 'deviantart',
		color: '#05CC47',
		logo: 'https://i.postimg.cc/Bb167CQb/deviantart.png',
		baseUrl: 'https://www.deviantart.com/',
	},
	{
		platform: 'dev.to',
		color: '#333333',
		logo: 'https://i.postimg.cc/B6zbCz3R/dev.png',
		baseUrl: 'https://dev.to/',
	},
	{
		platform: 'quora',
		color: '#B92B27',
		logo: 'https://i.postimg.cc/zftK905F/quora.png',
		baseUrl: 'https://www.quora.com/',
	},
	{
		platform: 'slack',
		color: '#4A154B',
		logo: 'https://i.postimg.cc/9MDZVZQ5/slack.png',
		baseUrl: 'https://slack.com/',
	},
	{
		platform: 'gitlab',
		color: '#FC6D26',
		logo: 'https://i.postimg.cc/fRscXVBm/gitlab.png',
		baseUrl: 'https://gitlab.com/',
	},
	{
		platform: 'stackoverflow',
		color: '#F48024',
		logo: 'https://i.postimg.cc/1XkYQy0P/1298710-stack-overflow-icon.png',
		baseUrl: 'https://stackoverflow.com/',
	},
	{
		platform: 'telegram',
		color: '#0088CC',
		logo: 'https://i.postimg.cc/WbLgLDRC/telegram.png',
		baseUrl: 'https://t.me/',
	},
	{
		platform: '',
		color: '#333333',
		logo: 'https://i.postimg.cc/Cxkcm2V6/icons8-web-50.png',
		baseUrl: '',
	},
];
